language: node_js
node_js:
    - "4"
script: node_modules/.bin/grunt unit:test
before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
before_script:
    - npm install & bower install
cache:
  directories:
    - node_modules
    - app/bower_components
notifications:
  slack: drtforgsa18f:OD19nZfXI42xWk5WFzflH75S
